### ISSUE TITLE
re-arrange text in CoC

### ISSUE THREAD

**Issue by astheriae** [GrafeasGroup/tor#103]
re-arrange bullet points to 

* Respect the Formatting
* Ask Us if You Need Help
* Be Aware of Your Surroundings
* Use Formal Language

**Comment by PejmanPoh** [comment]
Could I suggest placing "Ask Us if you need any help" at the bottom? It seems like a fail-safe option, like dialing 0 to get directly to customer rep because you can't find your solution in the phone system.

Please do this, and do this, and do this, and if you STILL don't know what is happening, ask us.

**Comment by itsthejoker** [comment]
Current layout:

**Be Aware of Your Surroundings**
**Use Formal Language**
**Respect the Formatting**
**Ask Us if You Need Help**

It's already at the bottom, but right now I think we suffer from people not fully reading the entire thing (or checking out halfway through or something).

**Comment by PejmanPoh** [comment]
@astheriae @itsthejoker, this change just requires a wiki edit. Shall we finalise this?

Everyone ok with:

*Respect the Formatting
*Be Aware of Your Surroundings
*Use Formal Language
*Ask Us if You Need Help

?

**Comment by PejmanPoh** [comment]
Alright, the order has been modified. Issue can be closed.
