### ISSUE TITLE
Add a short rules summary for each sub in u/ToR's comment

### ISSUE THREAD

**Issue by perryprog** [GrafeasGroup/tor#114]
Since an important rule we have is always follow the rules, i.e. report content that has visible usernames, it could be helpful to write a short bullet list for every sub that summarizes the rules that we need to pay attention to. For example, for QYBS:
- Only images and screenshots
- No identifying information

Something simple, like that.

It'd take a bit of work to initially write these summaries, but after that it should pay off.

**Comment by DavidArchibald** [comment]
It looks like we already have: https://www.reddit.com/r/TranscribersOfReddit/wiki/personalinformation and so that could start to kickstart it(or perhaps this inspired that?)

We could also perhaps programmatically pull rules from the subreddit to reduce manual labor or the need to constantly update. I also think it'd be useful to add the rules to /u/TranscribersofReddit's instructions on each post, perhaps that is what you intended, but you didn't explicitly say so, so I'm just stating it just in case.

**Comment by TheLonelyGhost** [comment]
We're already very chatty in the `claim`, `i accept`, etc. interactions. The bot posts multiple messages because we actually run out of room in a single comment box.

I don't think this is feasible to include the sub's rules in the bot's response, even if we could harvest the latest set of rules in some automated way.
