### ISSUE TITLE
Create a i18n object for easy and maintainable access to Strings

### ISSUE THREAD

**Issue by MaxVanDeursen** [GrafeasGroup/tor#190]
Right now each method or function using `i18n` messages to reply to a user or send a message to Slack accesses the dictionary which is parsed from the YAML. Instead I would suggest using some type of object which has these messages as attributes. This way the code changes are easier done when something is changed within said strings. 

Moreover, this will probably remove the need for the `_` helper function which puts the format underneath the message at hand, as this can then be done centrally within the described class.

**Comment by itsthejoker** [comment]
@TheLonelyGhost

**Comment by TheLonelyGhost** [comment]
I'm a bit unclear on the proposal here. Are you suggesting we make python classes for each language and, if a string needs to change, we modify that python code?

If so, that's where this came from (albeit not using the i18n library) before changing to use YAML instead. Reasons for changing to this were:

- I've talked with people new to Python and YAML at my day-job. They're far more comfortable editing YAML because it's simpler
- We're centralizing the strings used in user-facing messaging, less about providing translations. The name was more to indicate a standard pattern to follow
- With a simpler config syntax, YAML > JSON due to support for comments

**Comment by MaxVanDeursen** [comment]
I am suggesting to do something along the following:
- Keep the YAML files per language.
- Create a `StringTemplate` class which accepts a `lang` argument, just as `translation` in the `core.strings` module now does.
- Instead of `translation` being the raw dictionary, `StringTemplate` houses these messages as its attributes, allowing easier access. Moreover we can attach more logic to the instantiation of these messages, for example automatically attaching the bot's footer to the messages.

**Comment by Pf441** [comment]
Do we wish to work on this issue or do we put it in stand-by until Blossom is online?

**Comment by TheLonelyGhost** [comment]
Blossom is online now, so... go for it?

**Comment by TimJentzsch** [comment]
Not sure when this was added, but we had it for a long time already.
