### ISSUE TITLE
Add state for "accepted CoC, but not reviewed yet"

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor#197]
When a volunteer accepts the code of conduct, they can complete their first transcription. The process then states that they must be welcomed and reviewed by a mod, but there's nothing that stops them from continuing until their first transcription has been reviewed.

I think we can add a new state that will help solve this problem. Current flow:

- User has not worked with us before
- user accepts the CoC
  - username written to `accepted_CoC`
- user creates first transcription
- user potentially does a lot of transcriptions
- user is reviewed by Welcome team and given suggestions / official welcome

Proposed flow:

- user has not worked with us before
- accepts CoC
  - username written to `under_review`
- creates first transcription
  - while in this state, the bot will refuse to work with them and will not process any commands
- transcription is reviewed by a moderator
- moderator informs the bot that a review has taken place (maybe just `!ok` or something similar so we can use the existing mod commands functionality?)
  - username moved to `accepted_CoC`
- user can create new transcriptions at will

Idea credit: @Altrissa

**Comment by MaxVanDeursen** [comment]
I just want to document my current thoughts on this approach, and probably even more specifically on how we will implement this. To make this workflow possible, we have to make sure that the moderator informs the bot of the review being done. Although in essence this sounds simple, the current architecture should first be updated to use the Django User Groups for authorization. Even then, currently the way we will envoke requests on Blossom is through the ToR bot account. Hence, this authorization pipeline probably will not work in this situation, as the authorization is checked for ToR bot rather than the one actually submitting the request (e.g. the one commenting `done` or `!ok`).

I think we should first focus on making ToR bot and Blossom work with one another before switching our focus to this new workflow.

**Comment by TheLonelyGhost** [comment]
I'm pretty sure we are handling this with Bubbles today. I think it should probably stay managed with that bot.
