### ISSUE TITLE
Messages get drowned by the bot after some transcribing

### ISSUE THREAD

**Issue by fncybln** [GrafeasGroup/tor#209]
Opened the Issue to keep track of after a discord transcription.

Every time I transcribe something, I get two messages which usually say that everything went right. I don't read them because they (usually) say the same thing every time. So if there is something going wrong, there is a possibility i simply over-read it. 
To prevent that, it maybe would be a good idea to "sort" the bot replies to make the "failures" stand out? So that if I claimed the post successfully, the bot pings me via username (and I don't have to worry about anything + it is still easily accessible). If there is anything going wrong the bot replies to my "claim"/"done" and i get a standard message on the "reply" tab?

maybe another idea would be that after 10 or so transcribes the "successful" bot reply could just stop and we only get pinged when something goes wrong? The flair still changes so we still have an indicator.

discord discussion: https://discord.com/channels/318873523579781132/370200022735781898/830493599321423942

**Comment by itsthejoker** [comment]
Also as context from that conversation, some of our more high-activity transcribers reply directly from the inbox message, so if this is something that's added it will need to be configurable somehow in userland.

**Comment by Pf441** [comment]
I'm worried about two (three) main points:

* being pinged by the bot gives a pretty similar notification on desktop, so I'm not sure it will help much to separate the "successful" messages from the "wrong" ones. If I remember well, notifications can be filtered on mobile, but it's a bit wacky to remove all the "reply received" notifications to better detect the "mentioned in a message"
* silencing the "successful" messages is hazardous: if we don't expect the bot to reply if things go well, then people could transcribe even if the bot is down, since nobody expects a reply
* (more about technical stuff) "10 or so" is a bit vague. 10 transcriptions overall? 10 transcriptions in a day? If people can customize this setting, we'll need an extra database for that (or a solution like that, so maybe this point will be moot once the overhaul is complete).
