### ISSUE TITLE
Unclaim not working properly

### ISSUE THREAD

**Issue by itsthejoker** [GrafeasGroup/tor#216]
https://old.reddit.com/r/TranscribersOfReddit/comments/nv4e1o/suicidebywords_image_summer_always_hurts/

Submission should have:

- reply to `unclaim`
- changed status to unclaimed
- not removed submission

**Comment by MaxVanDeursen** [comment]
No message is sent in Slack, which means https://github.com/GrafeasGroup/tor/blob/3c3ed009d9d43d15a1183442f6a1fa90756222cb/tor/core/helpers.py#L286 has not been executed.

**Comment by MaxVanDeursen** [comment]
It does not seem like the API has failed to patch te submission; around the time of the `unclaim` being processed no 400+ HTTP codes are displayed.

**Comment by MaxVanDeursen** [comment]
```
Jun 08 13:54:00 localhost tor_moderator[12942]: WARNING | process_reply | 'Response' object has no attribute 'status'
Jun 08 13:54:00 localhost tor_moderator[12942]: WARNING | process_reply | Unable to process comment https://redd.it/nv4e1o by Kyle4961
```
In `tor`'s logs

**Comment by MaxVanDeursen** [comment]
The bug is because of https://github.com/GrafeasGroup/tor/blob/3c3ed009d9d43d15a1183442f6a1fa90756222cb/tor/core/helpers.py#L278

this uses the `patch` method of the `BlossomWrapper`, which in all honesty probably should have been a private method, as it does **not** wrap Blossom, instead returning a plain `Response` of the `requests` library. 

@itsthejoker How would you go about  this? What do you think of the following plan:
- Make `patch`, `get`, `delete`, `patch` to private methods, and introduce `update_submission` in the `BlossomWrapper`
- Bump the version of BlossomWrapper.
- Bump the version of BlossomWrapper in tor and adjust above code to use `update_submission` instead

**Comment by MaxVanDeursen** [comment]
![image](https://user-images.githubusercontent.com/15815926/121206627-ec3d4080-c878-11eb-83f9-29177a72d1c7.png)

**Comment by MaxVanDeursen** [comment]
Is fixed when https://github.com/GrafeasGroup/blossom-wrapper/issues/2 is implemented
