### ISSUE TITLE
Setup automated CI runner for pull requests

### ISSUE THREAD

**Issue by TheLonelyGhost** [GrafeasGroup/tor#32]
(per discussion in #31)

Though I'm not a big fan of Travis-CI, I can't deny that it has a killer free usage tier for open source projects. Either way, it would be loads better if we could have ANY CI system to run automated tests for the following:

- [ ] `pip install` works without error
- [ ] Automated tests are passing
- [ ] Changelog has changed in at least one commit of the current pull request

**Comment by itsthejoker** [comment]
I have a fair amount of experience getting TravisCI working (and actually have interacted with their engineering a few times) so this is something I can work on.

**Comment by TheLonelyGhost** [comment]
In that case, I may need your help on another open source project and some issues I've had with reading from PTY streams on Travis.

**Comment by NGTmeaty** [comment]
https://circleci.com/pricing/#build-linux

I've used CircleCI before, and it seems the free tier might work pretty well for us?

**Comment by itsthejoker** [comment]
I personally would rather stick with TravisCI because I actually already have a dev box set up that mirrors their infrastructure, which makes debugging builds way faster. Also, TravisCI's limitations for build time seem more sane than CircleCI's -- for Travis, builds terminate automatically after 120 minutes, which is completely understandable. Circle just allows 1500 minutes of build time, which means if a job gets stuck, we don't notice, and it runs for 25 hours, we can't do testing for the rest of the month.

**Comment by TheLonelyGhost** [comment]
Seconded about CircleCI. I like it a lot better, if only for how it uses containers for test environments. From what I've found, the free usage tier isn't as nice as other solutions. More specifically, it seems usage time limits are scoped to the user account, not the project.

I'm less worried about a test hanging (because we should be testing locally too, right?) and more about us limiting other projects from using CircleCI that might not work with Travis, especially if we hook this up to run incoming pull requests through CI. And that's the dream here, right?

If we'd like to spend the time eventually, I'd love to figure out how to hook up Gitlab-CI runners to github, or otherwise take advantage of gitlab's pipelines here. It's pretty non-trivial though and we would be better served with an immediate, mostly-okay solution than a perfect one.

**Comment by itsthejoker** [comment]
(TravisCI has the option to run everything in containers :P )

I'm doing some more research on this today. CircleCI seems valid -- most of my gripes come from not wanting to spread my projects out across different platforms that all do the same thing (since I'm already using TravisCI), but I also realize that this isn't really my project anymore ^_^

**Comment by TheLonelyGhost** [comment]
If Travis can handle containers (and I'd be very interested to see that) I'd highly recommend sticking with it. Free usage tier is much nicer and it's far more ubiquitous among projects on GitHub.

**Comment by itsthejoker** [comment]
https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments TravisCI runs containers by default unless you add `sudo: required`, which we might need for Tesseract; not sure yet. There is also built-in docker support: https://docs.travis-ci.com/user/docker/

**Comment by TheLonelyGhost** [comment]
I see some decisions only appeared in private conversations. To mirror here, I'm in favor of Travis CI since it appears to have comparable container support. What I'm most in favor of is running tests inside of a container like what gitlab-ci does. I could go on about what I like about gitlab, but for the sake of this issue, it appears too difficult to replicate on Travis or Circle CI.

Due to free usage tier limits and no significant benefit to Circle CI over Travis, that I can see, I'm voting for using Travis.
