### ISSUE TITLE
Validate author of "claim" is the same as author for "done"

### ISSUE THREAD

**Issue by TheLonelyGhost** [GrafeasGroup/tor#87]
Right now we're a bit lacking in some of our validations, specifically that the user saying "done" is the person who claimed the post originally. It's on the honor system right now. That makes me uncomfortable.

Your mission, should you choose to accept it, is to check the "claim" comment that had the bot respond with "the post is yours" (or similar) for the author and compare it to the author of a comment saying "done". If they match, continue with existing functionality. If they do not, error out and comment saying something like "you haven't claimed this post".

**Comment by perryprog** [comment]
That sounds like a very simple fix. I'll look into it in a bit.

**Comment by xanderyzwich** [comment]
@perryprog are you still working on this?

**Comment by perryprog** [comment]
Yes. See #88.

**Comment by Pf441** [comment]
ADD: right now, the bot will send the CoC message to the new user even if the post had already been claimed by another transcriber beforehand, and it can be disappointing for the new user. Especially if the post has been "stolen" in-between the "Claim" and "I accept". Example 1:

* new user sends "Claim". The bot sends them the Code of Conduct and asks for "I accept"
* another user claims the post. Since the post was unclaimed, the bot gives the post to them
* new user replies "I accept". The bot tells them that the post has already been claimed and to search for something else

This example can happen if it's a brand new user (with the 10-minutes delay between comments) or if they drag a bit.

Example 2 (more focused on this addendum):

* old user claims the post, and the bot gives it to them
* new user claims the post, and the bot sends them the Code of Conduct
* new user replies "I accept". The bot tells them that the post has already been claimed and to search for something else

Suggested feature(s):

* new user sends "Claim". The bot sends them the Code of Conduct and asks for "I accept"
* another user claims the post. Since the post has already been claimed (without "I accept" yet), the bot tells this user to search for another post

* old user claims the post, and the bot gives it to them
* new user claims the post, and the bot tells them to find another post, since that one had already been claimed

**Comment by TimJentzsch** [comment]
This should be fixed now, right? Could probably be closed.

**Comment by TheLonelyGhost** [comment]
Confirmed. It is fixed. 👍
