### ISSUE TITLE
Move current admin_commands system to decorator style

### ISSUE THREAD

**Issue by perryprog** [GrafeasGroup/tor#95]
Yes, we're changing it again.

[ Coming from here.](https://github.com/GrafeasGroup/tor/pull/94#issuecomment-359296531)

Basically simplify the command system once again, using a style similar to @arfie's style in the above PR. It should be possible to add commands without any config file at all, as well.

**Comment by arfie** [comment]
Sounds good! I want to explore ways to combine the two (user commands and admin commands), such as adding a keyword argument `mod_only` to the decorator that indicates if it's an admin command. The only potential roadblock I see is comment replies versus PMs (right now all user commands are comments and admin commands are usually done via PM). This could also probably be fixed by specifying in the decorator.

**Comment by TheLonelyGhost** [comment]
Note to self: Related to #94

**Comment by TheLonelyGhost** [comment]
Closed as stale. We can revisit this if we care that much. Please reopen if that's the case.
